name: TWRP Build (Codespaces)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
    - name: Checkout workflow repo
      uses: actions/checkout@v4

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y repo git openjdk-11-jdk curl python3

    - name: Initialize repo with minimal manifest (Lineage common only)
      run: |
        mkdir -p ~/twrp_build
        cd ~/twrp_build
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
        repo sync -j$(nproc) --force-sync --no-clone-bundle --no-tags

    - name: Clone device/kernel/vendor repos
      run: |
        cd ~/twrp_build
        git clone https://github.com/Omargamal7/twrp_device_samsung_a26xs -b twrp-12.1 device/samsung/a26xs
        git clone https://github.com/Omargamal7/twrp_device_samsung_s5e8825-common -b twrp-12.1 device/samsung/s5e8825-common
        git clone https://github.com/Omargamal7/android_kernel_samsung_universal8825 -b twrp-12.1 kernel/samsung/s5e8825
        git clone https://github.com/Omargamal7/proprietary_vendor_samsung_universal8825-common -b twrp-12.1 vendor/samsung

    - name: Setup build environment
      run: |
        cd ~/twrp_build
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch twrp_a26xs-eng

    - name: Build TWRP recovery image
      run: |
        cd ~/twrp_build
        mka recoveryimage 2>&1 | tee build.log
        if [ ! -f out/target/product/a26xs/recovery.img ]; then
          echo "Build failed: recovery.img not found"
          exit 1
        fi

    - name: Package build artifacts
      run: |
        cd ~/twrp_build
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        tar -czvf twrp_a26xs_${TIMESTAMP}.tar.gz -C out/target/product/a26xs recovery.img build.log

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: twrp_build
        path: ~/twrp_build/twrp_a26xs_*.tar.gz
