name: TWRP Builder (Windows Docker)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    name: Build TWRP in Docker
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build TWRP with Docker
        shell: pwsh
        run: |
          docker run --rm `
            -v "${env:GITHUB_WORKSPACE}:/workspace" `
            -v "${env:GITHUB_WORKSPACE}/ccache:/ccache" `
            -w /workspace `
            -e CCACHE_DIR=/ccache `
            -e CCACHE_COMPRESS=1 `
            -e CCACHE_MAXSIZE=20G `
            ghcr.io/lineageos/android:14 bash -c '
              set -eo pipefail
              echo ">>> Checking workspace size..."
              df -h /workspace

              echo ">>> Initializing repo..."
              repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1

              echo ">>> Syncing repo..."
              repo sync -j$(nproc) --force-sync --no-clone-bundle --no-tags

              echo ">>> Cloning device trees..."
              git clone https://github.com/Omargamal7/twrp_device_samsung_a26xs -b twrp-12.1 device/samsung/a26xs || true
              git clone https://github.com/Omargamal7/twrp_device_samsung_s5e8825-common -b twrp-12.1 device/samsung/s5e8825-common || true
              git clone https://github.com/Omargamal7/android_kernel_samsung_universal8825 -b twrp-12.1 kernel/samsung/s5e8825 || true
              git clone https://github.com/Omargamal7/proprietary_vendor_samsung_universal8825-common -b twrp-12.1 vendor/samsung || true

              echo ">>> Starting build..."
              export ALLOW_MISSING_DEPENDENCIES=true
              source build/envsetup.sh
              lunch twrp_a26xs-eng

              mka recoveryimage 2>&1 | tee /workspace/build.log

              if [ ! -f out/target/product/a26xs/recovery.img ]; then
                echo "❌ Build failed: recovery.img not found."
                exit 1
              else
                echo "✅ Build completed: recovery.img is ready."
              fi
            '
