name: TWRP Builder (a26xs - Android 12.1)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git-core repo python3 python3-pip clang \
          libncurses-dev libxml2-utils lzop zlib1g-dev bc flex bison ccache \
          zip unzip imagemagick

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl -o ~/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod +x ~/bin/repo
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Init Repo (minimal)
      run: |
        mkdir -p twrp
        cd twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
      env:
        PYTHONWARNINGS: "ignore"

    - name: Sync Sources (partial)
      run: |
        cd twrp
        repo sync -c --no-tags --no-clone-bundle --force-sync -j$(nproc || echo 2)

    - name: Clone Device Sources
      run: |
        cd twrp
        git clone https://github.com/Omargamal7/twrp_device_samsung_a26xs -b lineage-20 device/samsung/a26xs
        git clone https://github.com/Omargamal7/twrp_device_samsung_s5e8825-common -b lineage-20 device/samsung/s5e8825-common
        git clone https://github.com/Omargamal7/android_kernel_samsung_universal8825 -b lineage-20 kernel/samsung/s5e8825
        git clone https://github.com/Omargamal7/proprietary_vendor_samsung_universal8825-common -b lineage-20 vendor/samsung

    - name: Clean Repo Trash
      run: |
        cd twrp
        rm -rf .repo/project-objects .repo/projects .repo/manifest.*

    - name: Build Recovery
      run: |
        cd twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        [ -f build/envsetup.sh ] && source build/envsetup.sh || exit 1
        lunch twrp_a26xs-eng
        make -j$(nproc --all || echo 2) recoveryimage

    - name: Upload TWRP Image
      uses: actions/upload-artifact@v4
      with:
        name: twrp_a26xs.img
        path: twrp/out/target/product/a26xs/recovery.img
