### **Bypassing Windows Execution Policy for Scripts**  
If you're trying to bypass **Windows Execution Policy** (e.g., to run PowerShell scripts in Docker/GitHub Actions), here are **safe methods**:

---

### **1. For Local Windows Machines**  
#### **Method 1: Run PowerShell with `-ExecutionPolicy Bypass`**  
```powershell
powershell -ExecutionPolicy Bypass -File "script.ps1"
```
- **Why?** Temporarily overrides restrictions without changing system settings.  

#### **Method 2: Set Policy for Current Session**  
```powershell
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
```
- **Safe?** Only affects the current PowerShell window.  

#### **Method 3: Unblock Scripts (If Blocked by Windows)**  
```powershell
Unblock-File -Path "script.ps1"
```

---

### **2. For GitHub Actions (Docker/PowerShell Steps)**  
Your workflow already uses:  
```yaml
shell: powershell -ExecutionPolicy Bypass
```
- **This is correct** and safe in CI environments.  

#### **Alternative (Cleaner for GitHub Actions):**  
```yaml
steps:
  - name: Run Script
    shell: pwsh  # Uses PowerShell Core (modern)
    run: ./script.ps1
```
- **PowerShell Core (`pwsh`)** ignores execution policies by default.  

---

### **3. For Docker Containers (Linux/Windows)**  
If running PowerShell inside a **Windows-based Docker container**:  
```dockerfile
# In Dockerfile
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
```
Or pass policy flags at runtime:  
```powershell
docker run --rm mcr.microsoft.com/powershell pwsh -ExecutionPolicy Bypass -Command "Write-Host 'Hello'"
```

---

### **⚠️ Security Notes**  
- **Avoid `Set-ExecutionPolicy Unrestricted`** permanently.  
- **Signed scripts** are safer than bypassing policies.  
- **GitHub Actions** is isolated—bypassing policy there is low-risk.  

---

### **Your Workflow Fix**  
Your original YAML already handles this correctly:  
```yaml
shell: powershell -ExecutionPolicy Bypass  # ✅ Good for CI
```
No changes needed unless you prefer `shell: pwsh`.  

---

### **Need to Bypass for Other Reasons?**  
Let me know the context (e.g., local admin restrictions, corporate policies), and I’ll suggest alternatives! 
