name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, windows]

    steps:
      - name: Check E: Drive Space
        shell: powershell
        run: |
          Get-PSDrive E | Select-Object Used, Free | Format-Table -AutoSize

      - name: Create Test File
        shell: powershell
        run: |
          $path = "E:\\actions-runner"
          if (-not (Test-Path $path)) {
            New-Item -ItemType Directory -Path $path -Force
          }
          "This proves the runner works!" | Out-File -FilePath "$path\\test-success.txt" -Encoding utf8

      - name: Upload Proof
        uses: actions/upload-artifact@v4
        with:
          name: runner-proof
          path: E:/actions-runner/test-success.txt
